---

- name: Answering a prompt
  hosts: all
  gather_facts: no
  tasks:
    - name: Run multiple commands that require answering a prompt
      cisco.ios.ios_command:
        commands:
          - command: "clear counters g0/2"
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: "y"
          
          - command: "clear counters g0/3"
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: "y"
