---

- name: Play to install apache2 on Linux Mint
  hosts: all
  gather_facts: yes
  become: true
  tasks:

  - name: Update the apt repository index
    apt:
      update_cache: true
    when: ansible_distribution == "Linux Mint"

  - name: Install the apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Linux Mint"

  - name: Add PHP support for apache2
    apt:
      name: libapache2-mod-php
      state: present
    when: ansible_distribution == "Linux Mint"

  - name: Update the yum repository index for Rocky Linux
    dnf:
      update_cache: true
    when: ansible_distribution == "Rocky"

  - name: Install the httpd package
    dnf:
      name: httpd
      state: present
    when: ansible_distribution == "Rocky"

  - name: Add PHP support for httpd
    dnf:
      name: php
      state: present
    when: ansible_distribution == "Rocky"
